version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Display SSH Fingerprint
      - run:
          name: Display SSH Fingerprint
          command: |
            echo "Checking SSH key fingerprint..."
            mkdir -p ~/.ssh
            ssh-keygen -lf ~/.ssh/id_rsa

      # Enable SSH agent and add SSH key
      - add_ssh_keys:
          fingerprints:
            - "39:55:42:95:99:2e:df:f4:e7:fb:f3:a4:2c:b6:53:91"

# SSH into Server and Git Pull
- run:
    name: SSH into Server and Git Pull
    command: |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@54.170.49.64 "cd /home/ec2-user/circlci.sh && git pull"

