version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Display SSH Fingerprint
          command: |
            ssh-keygen -lf /home/ec2-user/.ssh/id_rsa

      - run:
          name: SSH into Server and Git Pull
          command: |
            ssh -i /home/ec2-user/.ssh/id_rsa ec2-user@34.253.191.231 "cd /home/ec2-user/circlci.sh/config.yml && git pull"
