version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Display SSH Fingerprint
      - run:
          name: Display SSH Fingerprint
          command: |
            echo "Checking SSH key fingerprint..."
            mkdir -p ~/.ssh
            ssh-keygen -lf ~/.ssh/id_rsa

      # Enable SSH agent and add SSH key
      - add_ssh_keys:
          fingerprints:
            - "3e:b8:53:74:d9:c5:e6:a0:d9:03:a7:d6:9b:bd:7d:54"

      # SSH into Server and Git Pull
      - run:
          name: SSH into Server and Git Pull
          command: |
            ssh -i ~/.ssh/id_rsa ec2-user@54.170.49.64 "cd /home/ec2-user/circlci.sh && git pull"
