version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python -m unittest discover tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

